"""Clear incorrect data from visit_log

Revision ID: fc0b796e15c8
Revises: aa1de63fedb1
Create Date: 2025-08-02 11:15:02.607547

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc0b796e15c8"
down_revision: Union[str, Sequence[str], None] = "aa1de63fedb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Очищаем все строки из таблицы visit_log
    op.execute("TRUNCATE TABLE visit_log")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
