# docker-compose.yml
name: fastapi-project

services:
  fastapi-service:
    container_name: fastapi-service
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    environment:
      ENV: prod
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
    # Убираем проброс портов, так как теперь через nginx
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      ENV: "prod"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - backend

  nginx:
    build:
      context: ..
      dockerfile: Docker/Dockerfile.nginx
    container_name: nginx-fastapi
    ports:
      - "80:80"
      # - "443:443" если нужен HTTPS
    depends_on:
      - fastapi-service
    networks:
      - backend
    restart: unless-stopped

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
