# deploy.yml
name: Deploy fastapi-service

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to server
        id: deploy
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB
          script: |
            cd /opt/fastapi-service
            echo "🔄 Обновление кода из main"
            git fetch origin main --depth=1
            git reset --hard FETCH_HEAD
            git clean -xfd

            echo "🛑 Остановка старых контейнеров..."
            docker compose -f Docker/docker-compose.yml down --remove-orphans

            echo "Сборка и запуск..."
            docker compose -f Docker/docker-compose.yml up -d --build

            echo "Ожидание запуска контейнеров..."
            sleep 10

            echo "Проверка статуса контейнеров..."
            # Добавляем цикл проверки с таймаутом
            max_attempts=7
            attempt=1
            while [ $attempt -le $max_attempts ]; do
              if docker compose -f Docker/docker-compose.yml ps --services --filter status=running | grep -q "postgres-db" && \
                 docker compose -f Docker/docker-compose.yml ps --services --filter status=running | grep -q "fastapi-service" && \
                 docker compose -f Docker/docker-compose.yml ps --services --filter status=running | grep -q "nginx-fastapi"; then
                echo "✅ Все контейнеры успешно запущены"
                break
              fi
              
              if [ $attempt -eq $max_attempts ]; then
                echo "❌ Превышено время ожидания запуска контейнеров"
                docker compose -f Docker/docker-compose.yml logs
                exit 1
              fi

              echo "⏳ Попытка $attempt из $max_attempts, ожидание 10 секунд..."
              sleep 10
              attempt=$((attempt + 1))
            done

            echo "✅ Deployment completed"
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Report Status
        uses: ./.github/actions/ci-report
        with:
          status: ${{ steps.deploy.outcome }}
          ci_secret: ${{ secrets.CI_SECRET }}
          ci_endpoint: ${{ secrets.CI_ENDPOINT }}
